// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Researcher_Management.Data;

#nullable disable

namespace Researcher_Management.Migrations
{
    [DbContext(typeof(ResercherDBContext))]
    [Migration("20230514171745_inittablecanbo")]
    partial class inittablecanbo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Researcher_Management.Data.CanBoNghienCuu", b =>
                {
                    b.Property<string>("Macanbonghiencuu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Chucdanhnghenghiep")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Chunhiemdetai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Dienthoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hocham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoacongtac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Macanbonghiencuu");

                    b.ToTable("canBoNghienCuu");
                });
#pragma warning restore 612, 618
        }
    }
}
