// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffManage.Data;

#nullable disable

namespace StaffManage.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    [Migration("20230505214949_DBUpdateTable")]
    partial class DBUpdateTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StaffManage.Data.CanBo", b =>
                {
                    b.Property<string>("Macanbo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bacluong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachinharieng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dienthoaicoquan")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Dienthoainharieng")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Gioitinh")
                        .HasColumnType("bit");

                    b.Property<string>("Hocham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hocvi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Luongcoban")
                        .HasColumnType("float");

                    b.Property<int>("Madonvi")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Namhocham")
                        .HasColumnType("int");

                    b.Property<int>("Namhocvi")
                        .HasColumnType("int");

                    b.Property<int>("Namsinh")
                        .HasColumnType("int");

                    b.HasKey("Macanbo");

                    b.ToTable("canBo");
                });

            modelBuilder.Entity("StaffManage.Data.DonVi", b =>
                {
                    b.Property<int>("Madonvi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madonvi"), 1L, 1);

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dienthoai")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nguoidungdau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tendonvi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Madonvi");

                    b.ToTable("donvi");
                });
#pragma warning restore 612, 618
        }
    }
}
