// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffManage.Data;

#nullable disable

namespace StaffManage.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    partial class StaffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StaffManage.Data.CanBo", b =>
                {
                    b.Property<string>("Macanbo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bacluong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachinharieng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dienthoaicoquan")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Dienthoainharieng")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Gioitinh")
                        .HasColumnType("bit");

                    b.Property<string>("Hocham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hocvi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Luongcoban")
                        .HasColumnType("float");

                    b.Property<int>("Madonvi")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Namhocham")
                        .HasColumnType("int");

                    b.Property<int>("Namhocvi")
                        .HasColumnType("int");

                    b.Property<int>("Namsinh")
                        .HasColumnType("int");

                    b.HasKey("Macanbo");

                    b.HasIndex("Madonvi");

                    b.ToTable("canBo");
                });

            modelBuilder.Entity("StaffManage.Data.ChucDanh", b =>
                {
                    b.Property<int>("Machucdanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Machucdanh"), 1L, 1);

                    b.Property<string>("Tenchucdanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Machucdanh");

                    b.ToTable("chucDanh");
                });

            modelBuilder.Entity("StaffManage.Data.ChucVu", b =>
                {
                    b.Property<int>("Machucvu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Machucvu"), 1L, 1);

                    b.Property<string>("Tenchucvu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Machucvu");

                    b.ToTable("chucVu");
                });

            modelBuilder.Entity("StaffManage.Data.CongTrinhKH_CN", b =>
                {
                    b.Property<int>("MacongtrinhKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MacongtrinhKH"), 1L, 1);

                    b.Property<string>("LoaicongtrinhKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MacongtrinhKH");

                    b.ToTable("congTrinhKH_CN");
                });

            modelBuilder.Entity("StaffManage.Data.DeTaiDuAnKHCNThamGia", b =>
                {
                    b.Property<int>("Madetai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madetai"), 1L, 1);

                    b.Property<string>("Tendetai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Madetai");

                    b.ToTable("deTaiDuAn");
                });

            modelBuilder.Entity("StaffManage.Data.DonVi", b =>
                {
                    b.Property<int>("Madonvi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madonvi"), 1L, 1);

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dienthoai")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nguoidungdau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tendonvi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Madonvi");

                    b.ToTable("donvi");
                });

            modelBuilder.Entity("StaffManage.Data.GiaiThuong", b =>
                {
                    b.Property<int>("Magiaithuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magiaithuong"), 1L, 1);

                    b.Property<string>("Hinhthuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Magiaithuong");

                    b.ToTable("giaiThuong");
                });

            modelBuilder.Entity("StaffManage.Data.KhenThuong", b =>
                {
                    b.Property<int>("Makhenthuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makhenthuong"), 1L, 1);

                    b.Property<string>("Tenkhenthuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Makhenthuong");

                    b.ToTable("khenThuong");
                });

            modelBuilder.Entity("StaffManage.Data.KinhNghiemKH_CN", b =>
                {
                    b.Property<int>("Mahinhthuchoidong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mahinhthuchoidong"), 1L, 1);

                    b.Property<string>("Hinhthuchoidong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mahinhthuchoidong");

                    b.ToTable("KinhNghiemKH&CN");
                });

            modelBuilder.Entity("StaffManage.Data.KyLuat", b =>
                {
                    b.Property<int>("Makyluat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makyluat"), 1L, 1);

                    b.Property<string>("Tenkyluat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Makyluat");

                    b.ToTable("kyLuat");
                });

            modelBuilder.Entity("StaffManage.Data.LinhVucNghienCuu", b =>
                {
                    b.Property<int>("Machuyennganh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Machuyennganh"), 1L, 1);

                    b.Property<string>("Tenchuyennganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Machuyennganh");

                    b.ToTable("linhVuc");
                });

            modelBuilder.Entity("StaffManage.Data.QuaTrinhDaoTao", b =>
                {
                    b.Property<int>("Mabacdaotao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mabacdaotao"), 1L, 1);

                    b.Property<string>("Bacdaotao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mabacdaotao");

                    b.ToTable("quaTrinhDaoTao");
                });

            modelBuilder.Entity("StaffManage.Data.TrinhDoNgoaiNgu", b =>
                {
                    b.Property<int>("Mangoaingu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mangoaingu"), 1L, 1);

                    b.Property<string>("Tenngoaingu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mangoaingu");

                    b.ToTable("trinhDoNgoaiNgu");
                });

            modelBuilder.Entity("StaffManage.Data.VanBangCanBo", b =>
                {
                    b.Property<int>("Mavanbang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mavanbang"), 1L, 1);

                    b.Property<string>("Tenvanbang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mavanbang");

                    b.ToTable("vanBang");
                });

            modelBuilder.Entity("StaffManage.Data.CanBo", b =>
                {
                    b.HasOne("StaffManage.Data.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("Madonvi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonVi");
                });
#pragma warning restore 612, 618
        }
    }
}
